version: '2'
services:
  kali:
    build:
      context: ./kali
    privileged: true
    #network_mode: "host"
    volumes:
      - "${SHARED_PATH}:/media/shared"
      - "./srv/root/.msf4:/root/.msf4"
